### ISSUE TITLE
Does not compile on centos 7 (Linux 3.10 - x86_64)

### ISSUE THREAD

**Issue by dupgit** [fhrbata/redirfs#1]
Compilation of redirfs/src ends with errors like :
avflt_check.c:50:26: erreur: ‘struct file’ has no member named ‘f_vfsmnt
avflt_check.c:274:4: erreur: too many arguments to function ‘dentry_open’
